import Head from 'next/head'
import Layout from '../components/layout'

export default function Home() {
  return (<>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <h1>Herzlich Willkommen</h1>
    <h2>auf der Homepage der freiwilligen Feuerwehr Rennertehausen</h2>
    <p>Diese Homepage befindet sich momentan noch im Aufbau. Daher kann es vorkommen, dass einige Links nicht wie gewohnt funktionieren</p>
  </>
  )
}
