name: upload-homepage

run-name: ${{ github.actor }} uploaded a new version of the homepage

on:
  push:
    branches:
      - 'master'

jobs:
  create_backup_job:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Configure SSH
        run: |
          mkdir ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/server.key
          chmod 600 ~/.ssh/server.key
          cat >> ~/.ssh/config << END
          HOST server
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/server.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{secrets.SSH_USER}}
          SSH_KEY: ${{secrets.SSH_KEY}}
          SSH_HOST: ${{secrets.SSH_HOST}}
      - name: Backup previous version
        run: ssh server bash ./createBackup.sh
      - name: Checkout repo
        uses: actions/checkout@v4.0.0
      - name: Upload new version
        run: rsync -azP --delete ./public/* server:./www/

